"""add users table

Revision ID: 310142569fff
Revises: 
Create Date: 2020-05-21 02:34:54.865837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310142569fff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
